version: '3.9'
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

  stagiaires:
    build: ./stagiaire-service
    container_name: stagiaire-container
    ports:
      - "3001:3000"
    environment:
      MONGO_URL: mongodb://db:27017
      MONGO_DB: bdformation
      MONGO_COLLECTION: stagiaires
    # volumes:
    #   - /app/node_modules
    depends_on:
      - db